# UTS-3 My Stories for You

### **Pilihan dan Tanggung Jawab**

#### Phase 1

Waktu itu akhir bulan, hari terakhir ujian, aku bersiap pulang dari kampus dengan motor ku. Motor yang sudah lama aku inginkan kehadirannya tapi tak pernah mau untuk memperjuangkannya. Memang aku tidak bertanggung jawab. Untungnya masih ada orang tua ku yang sanggup menanggung keinginan anaknya yang sangat tidak bertanggung jawab ini. Saat akan menghidupkan motor, aku mendengar percakapan dari sekumpulan orang di dekat ku.

“Eh, desas-desusnya kita mulai kegiatan itu akhir Juli nanti ya?” 

“Iya, gua juga denger gitu.” 

“Lu stay disini atau pulang?.”

“Gua balik dulu sih, masih lama juga.”

Ada beberapa hal yang aku sadari. Pertama, orang-orang tersebut adalah teman-temanku dari prodi yang sama dengan ku. Kedua, akhir Juli bukan waktu yang lama bagiku mengingat ini adalah libur semester genap yang biasanya adalah liburan yang paling lama. Ketiga, kepindahanku dari Jatinangor ke Bandung baru bisa dilakukan awal Juli sesuai dengan kesepakatan dengan pemilik rumah, yang mana hal itu akan semakin mempersempit waktu liburan ku. Keempat, mungkin orang yang bercakap di dekat ku tadi adalah orang Bandung atau orang Jakarta yang bisa bolak balik dengan gampangnya. Sementara aku orang Sumatera yang harus mikir berkali-kali mau pulang atau tidak.  Mengingat ongkos yang bagiku tidak murah dan perjalanan yang sangat melelahkan. Hasilnya masalah pulang atau tidak ini selalu menghantuiku hingga aku selesai pindahan dan akhirnya harus memutuskan.

“Pulang se lah pi, lah lamo ndak sobok, kangen Ayah.”

Kata-kata di atas yang membuatku mengambil keputusan untuk pulang. Meskipun saat itu aku sama sekali tidak yakin akan kembali tepat waktu.

#### Phase 2

Malam itu aku sudah kembali berada di tanah Jawa, tepatnya di Bandara Soekarno Hatta. Aku sedang menunggu bis yang akan berangkat ke Bandung. Saat menunggu bis tersebut,  aku bertemu salah satu kating yang secara tidak sengaja mengenaliku sebagai adik tingkatnya. 

“Mau ke Bandung juga ya?”

“Eh, iya kak.”

Aku dengan wajah bingung menatap kepadanya. Seketika dia langsung memperlihatkan bagian dalam jaketnya dengan lambang himpunan yang sangat aku kenal di bagian dada jaket tersebut. 

“Baru balik juga ya kak?”

Aku bertanya dengan polosnya, mengira setiap orang yang ada di Bandara pasti habis atau akan naik pesawat.

“Engga, cuman mau ngambil barang, nanti balik lagi.”

Aku coba cerna kata-katanya dan setelah aku tanya lebih lanjut ternyata beliau sedang magang di Bandara tersebut.

“Aku ga ikut kegiatan itu, yakali aku nolak magang buat kegiatan itu.”

Seketika aku tertegun. Lagi-lagi tentang pilihan.

#### Phase 3

Akhirnya aku tetap ikut kegiatan itu. Datang tepat waktu dan mencoba menikmati. Setelah menjalani hari pertama, aku sangat menikmati dan mulai merasakan kalau aku akan dapat banyak hal di kegiatan ini. Namun hal itu sedikit memudar pada hari kedua. Aku mulai merasakan bagaimana perpeloncoan yang sering dibicarakan orang-orang kepadaku. Hatiku berontak. Aku tidak suka diteriaki. Aku tidak pernah menghormati orang hanya karena ia bisa berteriak. Banyak cara yang lebih elegan agar bisa dihormati. 

Akhirnya aku jalani sisa kegiatan dengan setengah hati. Sambil berusaha untuk tetap teguh pada pendirianku yaitu aku harus menyelesaikan sesuatu yang sudah kumulai.

Malam itu di Bumi Kiara Payung aku merasakan bahwa kegiatan ini akan segera berakhir. Aku akan segera menuntaskan tanggung jawabku. Namun hal itu pupus beberapa hari setelahnya. Ternyata masih banyak yang harus kulakukan. Masih banyak tanggung jawab yang harus aku selesaikan. Aku masih teguh pada pendirianku. Meskipun kujalani dengan setengah hati saja.
